spring:
  application:
    name: loan-service
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/loan_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: loan-service
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    correlation: [loan-service,%X{traceId:-},%X{spanId:-}]